rl.question('Enter File path to open ', (answer) => {  
fs.open(answer, 'rr', (err, fd) => {
fs.open(answer, 'rr', (err, fd) => {
fs.open(answer, 'rr', (err, fd) => {
fs.open(answer, 'rr', (err, fd) => {
fs.open(answer, 'rr', (err, fd) => {
fs.open(answer, 'rr', (err, fd) => {
fs.open(answer, 'rr', (err, fd) => {
fs.open(answer, 'rr', (err, fd) => {
fs.open(answer, 'rr', (err, fd) => {
fs.open(answer, 'rr', (err, fd) => {
fs.open(answer, 'rr', (err, fd) => {
fs.open(answer, 'rr', (err, fd) => {
fs.open(answer, 'rr', (err, fd) => {
fs.open(answer, 'rr', (err, fd) => {
fs.open(answer, 'rr', (err, fd) => {
fs.open(answer, 'rr', (err, fd) => {
fs.open(answer, 'rr', (err, fd) => {
fs.open(answer, 'rr', (err, fd) => {
fs.open(answer, 'rr', (err, fd) => {
fs.open(answer, 'rr', (err, fd) => {
fs.open(answer, 'rr', (err, fd) => {
fs.open(answer, 'rr', (err, fd) => {
fs.open(answer, 'rr', (err, fd) => {
fs.open(answer, 'rr', (err, fd) => {

